FROM python:3.6

MAINTAINER Rishat Sharafiev <rishatsharafiev@ya.ru>

# update pip
RUN pip install --upgrade pip

# install pipenv
RUN pip3 install --upgrade pipenv

# install application
COPY ./ /app
WORKDIR /app
RUN pipenv install --deploy --system # --skip-lock

RUN  python manage.py collectstatic --noinput

CMD  ['/bin/sh','-c','python manage.py migrate --noinput && python cherry.py']
