# Generated by Django 2.1.1 on 2018-10-11 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=255, verbose_name='Номенклатура')),
                ('brand', models.CharField(max_length=64, verbose_name='Бренд')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('vendor_code', models.CharField(max_length=32, verbose_name='Артикул')),
                ('nomenclature_group', models.CharField(max_length=32, verbose_name='Номенклатурная группа')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Оптовая цена')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Розничная цена')),
                ('gender', models.CharField(choices=[('man', 'М'), ('woman', 'Ж')], max_length=1, verbose_name='Пол')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpc.Good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('first_file', models.FileField(upload_to='', verbose_name='Первый файл(excel)')),
                ('second_file', models.FileField(upload_to='', verbose_name='Второй файл(excel)')),
                ('zip_file', models.FileField(upload_to='', verbose_name='Zip файл')),
                ('picture_path', models.FilePathField(verbose_name='Путь до изображений')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpc.Task', verbose_name='Задача'),
        ),
    ]
