# Generated by Django 2.1.1 on 2018-10-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpc', '0002_remove_task_picture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Новый'), (1, 'В обработке'), (2, 'Закончен'), (3, 'Ошибка')], default=0, verbose_name='Статус'),
        ),
    ]
