# Generated by Django 2.1.1 on 2018-10-11 17:48

import apps.bpc.models.task
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpc', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='first_file',
            field=models.FileField(upload_to=apps.bpc.models.task.get_file_path_1, verbose_name='Первый файл(excel)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='second_file',
            field=models.FileField(upload_to=apps.bpc.models.task.get_file_path_2, verbose_name='Второй файл(excel)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='zip_file',
            field=models.FileField(upload_to=apps.bpc.models.task.get_file_path_3, verbose_name='Zip файл'),
        ),
    ]
