# Generated by Django 2.1.1 on 2018-10-11 21:39

import apps.bpc.models.task
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpc', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='task',
            name='first_file',
            field=models.FileField(upload_to=apps.bpc.models.task.get_file_path, verbose_name='Первый файл(xlsx)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='second_file',
            field=models.FileField(upload_to=apps.bpc.models.task.get_file_path, verbose_name='Второй файл(xlsx)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='zip_file',
            field=models.FileField(upload_to=apps.bpc.models.task.get_file_path, verbose_name='Zip файл'),
        ),
    ]
