# Generated by Django 2.1.1 on 2018-10-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpc', '0004_auto_20181011_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Мужской'), (1, 'Женский'), (2, 'Детский'), (3, 'Подростковый'), (4, '')], verbose_name='Пол'),
        ),
    ]
