# Generated by Django 2.1.5 on 2019-01-16 05:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Атрибуты'),
        ),
    ]
