# Generated by Django 2.1.5 on 2019-01-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0002_auto_20190116_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='online_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
        migrations.AddField(
            model_name='product',
            name='back_picture',
            field=models.TextField(blank=True, null=True, verbose_name='Задний план'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_html',
            field=models.TextField(blank=True, null=True, verbose_name='Html описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_picture',
            field=models.TextField(blank=True, null=True, verbose_name='Передний план'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROGRESS', 'В обработке'), ('DONE', 'Закончен'), ('ERROR', 'Ошибка')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(verbose_name='Ссылка для сбора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
    ]
