# Generated by Django 2.1.5 on 2019-02-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0006_auto_20190212_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fcmoto.Page', verbose_name='Страница'),
        ),
    ]
