# Generated by Django 2.1.5 on 2019-02-21 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0008_auto_20190214_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(default='', max_length=255, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='category',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Наценка (%)'),
        ),
    ]
