# Generated by Django 2.1.5 on 2019-02-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0009_auto_20190221_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('meta_keywords', models.CharField(max_length=255, verbose_name='META Keywords')),
                ('meta_description', models.TextField(verbose_name='META Description')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка на витрину')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmoto.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория - информация',
                'verbose_name_plural': 'Категории - информация',
            },
        ),
    ]
