# Generated by Django 2.1.5 on 2019-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0010_categoryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.TextField(verbose_name='Ссылка на категорию'),
        ),
    ]
