# Generated by Django 2.1.5 on 2019-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0011_auto_20190227_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfo',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на витрину'),
        ),
    ]
