# Generated by Django 2.1.5 on 2019-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcmoto', '0012_auto_20190306_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_url_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название url + цвет'),
        ),
    ]
